import { jsxs as _jsxs, jsx as _jsx, Fragment as _Fragment } from "react/jsx-runtime";
// src/components/admin/CreateReservationDialog.tsx
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ArrowRight, ArrowLeft } from "lucide-react";
import { CreateReservationProvider } from "@/contexts/CreateReservationProvider";
import { useCreateReservationContext } from "@/contexts/CreateReservationContext";
import { CreateReservationStep1Details } from "./CreateReservationStep1Details";
import { CreateReservationStep2Accessories } from "./CreateReservationStep2Accessories";
import FinancialSummaryBlock from "@/components/shared/FinancialSummaryBlock";
// Внутренний компонент, который использует Context
const CreateReservationDialogContent = () => {
    const { step, setStep, form, users, isLoadingUsers, equipmentSearch, setEquipmentSearch, isLoadingEquipment, filteredAndGroupedEquipment, availabilityMap, equipmentWithAccessories, isLoadingAvailability, hasConflictsInSelection, isSubmitting, handleNextStep, onSubmit, handleCloseDialog, financialData } = useCreateReservationContext();
    const { formState: { isValid } } = form;
    const formId = "create-reservation-admin-form";
    return (_jsxs(DialogContent, { className: "sm:max-w-[700px] h-[90vh] flex flex-col p-0", children: [_jsxs(DialogHeader, { className: "p-6 pb-4", children: [_jsxs(DialogTitle, { children: ["\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u043D\u043E\u0432\u044B\u0439 \u0440\u0435\u0437\u0435\u0440\u0432 (\u0428\u0430\u0433 ", step === 'details' ? 1 : 2, " \u0438\u0437 2)"] }), _jsx(DialogDescription, { children: step === 'details'
                            ? "Выберите клиента, даты и оборудование для создания."
                            : "Выберите дополнительные аксессуары для позиций в резерве." })] }), _jsx("div", { className: "flex-1 overflow-y-auto px-6", children: _jsx("form", { id: formId, onSubmit: onSubmit, className: "contents", children: step === 'details' ? (_jsx(CreateReservationStep1Details, { form: form, users: users, isLoadingUsers: isLoadingUsers, equipmentSearch: equipmentSearch, setEquipmentSearch: setEquipmentSearch, isLoadingEquipment: isLoadingEquipment, filteredAndGroupedEquipment: filteredAndGroupedEquipment, availabilityMap: availabilityMap })) : (_jsx(CreateReservationStep2Accessories, {})) }) }), _jsx(DialogFooter, { className: "p-6 pt-4 border-t items-center", children: step === 'details' ? (_jsxs(_Fragment, { children: [_jsx(FinancialSummaryBlock, { priceDetails: financialData.priceDetails, accessoriesDailyTotal: 0, promoCode: financialData.promoCode, setPromoCode: financialData.setPromoCode, applyPromoCode: financialData.applyPromoCode, removePromoCode: financialData.removePromoCode, promoCodeMessage: financialData.promoCodeMessage, isLoading: isLoadingAvailability || financialData.isCalculatingPrice, isApplyingPromoCode: financialData.isApplyingPromoCode, isSubmitting: isSubmitting, isFormValid: isValid, hasConflicts: hasConflictsInSelection, variant: "admin", showActions: false }), _jsx(Button, { type: "button", variant: "ghost", onClick: handleCloseDialog, children: "\u041E\u0442\u043C\u0435\u043D\u0430" }), _jsxs(Button, { type: "button", onClick: handleNextStep, disabled: !isValid || isSubmitting || hasConflictsInSelection || isLoadingAvailability, children: [equipmentWithAccessories.length > 0 ? "Далее" : "Создать резерв", equipmentWithAccessories.length > 0 && _jsx(ArrowRight, { className: "ml-2 h-4 w-4" })] })] })) : (_jsxs(_Fragment, { children: [_jsx(FinancialSummaryBlock, { priceDetails: financialData.priceDetails, accessoriesDailyTotal: 0, promoCode: financialData.promoCode, setPromoCode: financialData.setPromoCode, applyPromoCode: financialData.applyPromoCode, removePromoCode: financialData.removePromoCode, promoCodeMessage: financialData.promoCodeMessage, isLoading: isLoadingAvailability || financialData.isCalculatingPrice, isApplyingPromoCode: financialData.isApplyingPromoCode, isSubmitting: isSubmitting, isFormValid: isValid, hasConflicts: hasConflictsInSelection, variant: "admin", showActions: false }), _jsxs(Button, { type: "button", variant: "ghost", onClick: () => setStep('details'), className: "mr-auto", children: [_jsx(ArrowLeft, { className: "mr-2 h-4 w-4" }), " \u041D\u0430\u0437\u0430\u0434"] }), _jsx(Button, { type: "button", variant: "ghost", onClick: handleCloseDialog, children: "\u041E\u0442\u043C\u0435\u043D\u0430" }), _jsx(Button, { type: "submit", form: formId, disabled: isSubmitting, children: isSubmitting ? "Создание..." : "Создать резерв" })] })) })] }));
};
// Основной компонент с Provider
export default function CreateReservationDialog({ isOpen, onClose }) {
    return (_jsx(Dialog, { open: isOpen, onOpenChange: onClose, children: _jsx(CreateReservationProvider, { isOpen: isOpen, onClose: onClose, children: _jsx(CreateReservationDialogContent, {}) }) }));
}
