import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/components/admin/EquipmentTableRow.tsx
import { TableCell, TableRow } from "@/components/ui/table";
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import { MoneyText } from "@/components/ui/money-text";
import { Edit, Trash2, Copy } from "lucide-react";
import { getConditionVariantClass } from "@/constants/equipmentConstants";
export const EquipmentTableRow = ({ item, isSelected, isManager, isDeleting, onSelectItem, onEdit, onDelete, onCopy }) => (_jsxs(TableRow, { children: [isManager && (_jsx(TableCell, { children: _jsx(Checkbox, { checked: isSelected, onCheckedChange: (checked) => onSelectItem(item.id, Boolean(checked)) }) })), _jsx(TableCell, { className: "font-medium", children: item.equipment_type }), _jsx(TableCell, { children: item.brand }), _jsx(TableCell, { children: item.name }), _jsx(TableCell, { children: item.serial_number || "—" }), _jsx(TableCell, { children: _jsx("span", { className: `text-xs px-2 py-1 rounded-full font-medium ${getConditionVariantClass(item.condition)}`, children: item.condition }) }), _jsx(TableCell, { className: "font-medium", children: _jsx(MoneyText, { value: item.daily_rate }) }), isManager && (_jsx(TableCell, { children: _jsxs("div", { className: "flex gap-2", children: [_jsx(Button, { variant: "outline", size: "icon", onClick: () => onEdit(item), "aria-label": `Редактировать ${item.name}`, children: _jsx(Edit, { className: "h-4 w-4", "aria-hidden": "true" }) }), _jsx(Button, { variant: "outline", size: "icon", onClick: () => onCopy(item), "aria-label": `Скопировать ${item.name}`, children: _jsx(Copy, { className: "h-4 w-4", "aria-hidden": "true" }) }), _jsx(Button, { variant: "destructive", size: "icon", onClick: () => onDelete(item.id), disabled: isDeleting, "aria-label": `Удалить ${item.name}`, children: _jsx(Trash2, { className: "h-4 w-4", "aria-hidden": "true" }) })] }) }))] }));
