# rental-app-main/Dockerfile.frontend

# --- ЭТАП 1: Сборка ---
FROM node:20-alpine as build
WORKDIR /app

# Пути теперь относительны папки rental-app-main
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# --- ЭТАП 2: Подача ---
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html

# Копируем конфигурацию nginx для разработки
COPY nginx/nginx.dev.conf /etc/nginx/conf.d/default.conf

# Строка `COPY nginx.conf` удалена, так как этим теперь управляет docker-compose.yml
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]