"""Add cascade delete to payments user_id foreign key

Revision ID: 471bd97fd27e
Revises: 8a94d05ff759
Create Date: 2025-10-27 21:55:53.931923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '471bd97fd27e'
down_revision: Union[str, None] = '8a94d05ff759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_audit_logs_created_at'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_event_category'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_event_type'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_ip_address'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_request_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_session_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_severity'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_user_email'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_user_id'), table_name='security_audit_logs')
    op.drop_table('security_audit_logs')
    op.drop_index(op.f('ix_balance_history_created_at'), table_name='balance_history')
    op.drop_index(op.f('ix_balance_history_operation_type'), table_name='balance_history')
    op.drop_index(op.f('ix_balance_history_rental_id'), table_name='balance_history')
    op.drop_index(op.f('ix_balance_history_user_id'), table_name='balance_history')
    op.drop_index(op.f('ix_equipment_brand'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_condition'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_type'), table_name='equipment')
    op.drop_index(op.f('ix_holiday_rules_created_by_id'), table_name='holiday_rules')
    op.drop_index(op.f('ix_holidays_created_by_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_rule_id'), table_name='holidays')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_rental_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_type'), table_name='payments')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_constraint(op.f('payments_user_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_promo_codes_created_by_id'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_expires_at'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_is_active'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_specific_to_user_id'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_valid_from'), table_name='promo_codes')
    op.drop_index(op.f('ix_rentals_created_at'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_created_by_id'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_end_date'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_reservation_id'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_start_date'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_updated_at'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_user_id'), table_name='rentals')
    op.drop_index(op.f('ix_reservations_created_at'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_end_date'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_promo_code_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_start_date'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.create_index(op.f('ix_reservations_start_date'), 'reservations', ['start_date'], unique=False)
    op.create_index(op.f('ix_reservations_promo_code_id'), 'reservations', ['promo_code_id'], unique=False)
    op.create_index(op.f('ix_reservations_end_date'), 'reservations', ['end_date'], unique=False)
    op.create_index(op.f('ix_reservations_created_at'), 'reservations', ['created_at'], unique=False)
    op.create_index(op.f('ix_rentals_user_id'), 'rentals', ['user_id'], unique=False)
    op.create_index(op.f('ix_rentals_updated_at'), 'rentals', ['updated_at'], unique=False)
    op.create_index(op.f('ix_rentals_start_date'), 'rentals', ['start_date'], unique=False)
    op.create_index(op.f('ix_rentals_reservation_id'), 'rentals', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_rentals_end_date'), 'rentals', ['end_date'], unique=False)
    op.create_index(op.f('ix_rentals_created_by_id'), 'rentals', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_rentals_created_at'), 'rentals', ['created_at'], unique=False)
    op.create_index(op.f('ix_promo_codes_valid_from'), 'promo_codes', ['valid_from'], unique=False)
    op.create_index(op.f('ix_promo_codes_specific_to_user_id'), 'promo_codes', ['specific_to_user_id'], unique=False)
    op.create_index(op.f('ix_promo_codes_is_active'), 'promo_codes', ['is_active'], unique=False)
    op.create_index(op.f('ix_promo_codes_expires_at'), 'promo_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_promo_codes_created_by_id'), 'promo_codes', ['created_by_id'], unique=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_user_id_fkey'), 'payments', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_payments_transaction_type'), 'payments', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_payments_rental_id'), 'payments', ['rental_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_holidays_rule_id'), 'holidays', ['rule_id'], unique=False)
    op.create_index(op.f('ix_holidays_created_by_id'), 'holidays', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_holiday_rules_created_by_id'), 'holiday_rules', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_equipment_equipment_type'), 'equipment', ['equipment_type'], unique=False)
    op.create_index(op.f('ix_equipment_condition'), 'equipment', ['condition'], unique=False)
    op.create_index(op.f('ix_equipment_brand'), 'equipment', ['brand'], unique=False)
    op.create_index(op.f('ix_balance_history_user_id'), 'balance_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_balance_history_rental_id'), 'balance_history', ['rental_id'], unique=False)
    op.create_index(op.f('ix_balance_history_operation_type'), 'balance_history', ['operation_type'], unique=False)
    op.create_index(op.f('ix_balance_history_created_at'), 'balance_history', ['created_at'], unique=False)
    op.create_table('security_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('request_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('failure_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('security_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_security_audit_logs_user_id'), 'security_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_user_email'), 'security_audit_logs', ['user_email'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_severity'), 'security_audit_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_session_id'), 'security_audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_request_id'), 'security_audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_ip_address'), 'security_audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_event_type'), 'security_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_event_category'), 'security_audit_logs', ['event_category'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_created_at'), 'security_audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
