"""Add telegram_username to User model

Revision ID: 59f726050559
Revises: e3f4a5b6c7d8
Create Date: 2025-09-30 01:06:54.930584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f726050559'
down_revision: Union[str, None] = 'e3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_username', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_telegram_username'), 'users', ['telegram_username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_username'), table_name='users')
    op.drop_column('users', 'telegram_username')
    # ### end Alembic commands ###
