"""Add cascade delete to all user foreign keys

Revision ID: 6d439243b533
Revises: 471bd97fd27e
Create Date: 2025-10-27 21:56:07.917688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d439243b533'
down_revision: Union[str, None] = '471bd97fd27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('balance_history_user_id_fkey'), 'balance_history', type_='foreignkey')
    op.create_foreign_key(None, 'balance_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('rentals_user_id_fkey'), 'rentals', type_='foreignkey')
    op.create_foreign_key(None, 'rentals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('reservations_user_id_fkey'), 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(op.f('reservations_user_id_fkey'), 'reservations', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.create_foreign_key(op.f('rentals_user_id_fkey'), 'rentals', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'balance_history', type_='foreignkey')
    op.create_foreign_key(op.f('balance_history_user_id_fkey'), 'balance_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
