"""Create initial tables

Revision ID: 9290ae79b0d3
Revises: 
Create Date: 2025-09-13 15:05:27.964374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9290ae79b0d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('accessory_type', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessories_accessory_type'), 'accessories', ['accessory_type'], unique=False)
    op.create_index(op.f('ix_accessories_id'), 'accessories', ['id'], unique=False)
    op.create_index(op.f('ix_accessories_name'), 'accessories', ['name'], unique=False)
    op.create_table('associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_associations_id'), 'associations', ['id'], unique=False)
    op.create_index(op.f('ix_associations_name'), 'associations', ['name'], unique=True)
    op.create_table('duration_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=False, comment='Минимальное количество дней для скидки (включительно)'),
    sa.Column('discount_percentage', sa.Integer(), nullable=False, comment='Процент скидки'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('min_days')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('daily_rate', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('last_maintenance', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('privacy_policy_accepted', sa.Boolean(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('association_equipment_association',
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('association_id', 'equipment_id')
    )
    op.create_table('equipment_accessories',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('accessory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessories.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('equipment_id', 'accessory_id')
    )
    op.create_table('holiday_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False, comment="Тип правила, например 'weekly' или 'public_import'"),
    sa.Column('parameters', sa.JSON(), nullable=False, comment="Параметры правила, например {'day_of_week': 6} для воскресенья"),
    sa.Column('description', sa.String(), nullable=False, comment='Описание правила для админа'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True, comment='Краткое описание для менеджеров'),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True, comment='Дата начала действия'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Дата истечения срока'),
    sa.Column('max_uses', sa.Integer(), nullable=True, comment='Общий лимит использований'),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=True, comment='Лимит на одного пользователя'),
    sa.Column('min_order_amount', sa.Float(), nullable=True, comment='Минимальная сумма заказа для активации'),
    sa.Column('specific_to_user_id', sa.Integer(), nullable=True, comment='Если код персональный'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['specific_to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_index(op.f('ix_promo_codes_id'), 'promo_codes', ['id'], unique=False)
    op.create_table('holidays',
    sa.Column('date', sa.Date(), nullable=False, comment='Дата выходного дня'),
    sa.Column('description', sa.String(), nullable=True, comment='Название (например, Новый год)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True, comment='ID правила, которым создан этот выходной'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['holiday_rules.id'], ),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=False)
    op.create_table('promo_code_applicable_types',
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.PrimaryKeyConstraint('promo_code_id', 'type_name')
    )
    op.create_table('promo_code_equipment',
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.PrimaryKeyConstraint('promo_code_id', 'equipment_id')
    )
    op.create_table('promo_code_usages',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'promo_code_id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_table('rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('promo_code', sa.String(), nullable=True),
    sa.Column('final_cost', sa.Float(), nullable=True),
    sa.Column('deposit_amount', sa.Float(), nullable=True),
    sa.Column('prepayment_amount', sa.Float(), nullable=False),
    sa.Column('notes_on_issue', sa.Text(), nullable=True),
    sa.Column('notes_on_return', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id')
    )
    op.create_index(op.f('ix_rentals_status'), 'rentals', ['status'], unique=False)
    op.create_table('reservation_accessories',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('accessory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessories.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('reservation_id', 'equipment_id', 'accessory_id')
    )
    op.create_table('reservation_equipment',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('reservation_id', 'equipment_id')
    )
    op.create_table('balance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False, comment='Сумма операции. Отрицательная для списания, положительная для начисления.'),
    sa.Column('operation_type', sa.String(), nullable=False, comment='Тип операции (e.g., rental_debit, early_return_credit)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание операции'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rental_accessories',
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('accessory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessories.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rental_id', 'equipment_id', 'accessory_id')
    )
    op.create_table('rental_equipment',
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rental_id', 'equipment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rental_equipment')
    op.drop_table('rental_accessories')
    op.drop_table('payments')
    op.drop_table('balance_history')
    op.drop_table('reservation_equipment')
    op.drop_table('reservation_accessories')
    op.drop_index(op.f('ix_rentals_status'), table_name='rentals')
    op.drop_table('rentals')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_table('promo_code_usages')
    op.drop_table('promo_code_equipment')
    op.drop_table('promo_code_applicable_types')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_promo_codes_id'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_table('holiday_rules')
    op.drop_table('equipment_accessories')
    op.drop_table('association_equipment_association')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('equipment')
    op.drop_table('duration_discounts')
    op.drop_index(op.f('ix_associations_name'), table_name='associations')
    op.drop_index(op.f('ix_associations_id'), table_name='associations')
    op.drop_table('associations')
    op.drop_index(op.f('ix_accessories_name'), table_name='accessories')
    op.drop_index(op.f('ix_accessories_id'), table_name='accessories')
    op.drop_index(op.f('ix_accessories_accessory_type'), table_name='accessories')
    op.drop_table('accessories')
    # ### end Alembic commands ###
