"""Change ondelete behavior for balance_history to SET NULL

Revision ID: d02198de6260
Revises: 9290ae79b0d3
Create Date: 2025-09-25 00:10:36.988584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02198de6260'
down_revision: Union[str, None] = '9290ae79b0d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('balance_history_rental_id_fkey'), 'balance_history', type_='foreignkey')
    op.create_foreign_key(None, 'balance_history', 'rentals', ['rental_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'balance_history', type_='foreignkey')
    op.create_foreign_key(op.f('balance_history_rental_id_fkey'), 'balance_history', 'rentals', ['rental_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
