"""Add BrandSystem model and m2m relationship with Equipment

Revision ID: dc7cf2a3570f
Revises: f1a2b3c4d5e6
Create Date: 2025-10-06 21:44:48.212256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7cf2a3570f'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Создаем таблицу brand_systems
    op.create_table('brand_systems',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_systems_id'), 'brand_systems', ['id'], unique=False)
    op.create_index(op.f('ix_brand_systems_name'), 'brand_systems', ['name'], unique=True)
    
    # Создаем ассоциативную таблицу для связи многие-ко-многим
    op.create_table('brand_system_equipment_association',
        sa.Column('brand_system_id', sa.Integer(), nullable=False),
        sa.Column('equipment_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['brand_system_id'], ['brand_systems.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('brand_system_id', 'equipment_id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаляем ассоциативную таблицу
    op.drop_table('brand_system_equipment_association')
    
    # Удаляем таблицу brand_systems
    op.drop_index(op.f('ix_brand_systems_name'), table_name='brand_systems')
    op.drop_index(op.f('ix_brand_systems_id'), table_name='brand_systems')
    op.drop_table('brand_systems')
    
    # ### end Alembic commands ###
