"""Add packs table

Revision ID: e3f4a5b6c7d8
Revises: d02198de6260
Create Date: 2025-01-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f4a5b6c7d8'
down_revision: Union[str, None] = 'd02198de6260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Создаем таблицу packs
    op.create_table('packs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packs_id'), 'packs', ['id'], unique=False)
    
    # Создаем связующую таблицу pack_equipment_association
    op.create_table('pack_equipment_association',
        sa.Column('pack_id', sa.Integer(), nullable=False),
        sa.Column('equipment_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('pack_id', 'equipment_id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаляем связующую таблицу
    op.drop_table('pack_equipment_association')
    
    # Удаляем таблицу packs
    op.drop_index(op.f('ix_packs_id'), table_name='packs')
    op.drop_table('packs')
    
    # ### end Alembic commands ###
