import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Card, CardHeader } from "@/components/ui/card";
import { User, Phone, Mail } from "lucide-react";
export default function ReceiptClientInfo({ user, isCompact = false, useCard = true }) {
    const content = (_jsxs(_Fragment, { children: [_jsxs("h3", { className: `flex items-center gap-2 ${isCompact ? 'text-sm' : 'text-lg'} font-semibold ${!useCard ? 'mb-1' : ''}`, children: [_jsx(User, { className: isCompact ? "w-3 h-3" : "w-5 h-5" }), "\u0418\u043D\u0444\u043E\u0440\u043C\u0430\u0446\u0438\u044F \u043E \u043A\u043B\u0438\u0435\u043D\u0442\u0435"] }), isCompact ? (_jsxs("div", { className: "space-y-1", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs font-medium text-gray-600", children: "\u0424\u0418\u041E" }), _jsx("p", { className: "text-sm font-semibold", children: user.full_name })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Mail, { className: "w-3 h-3 text-gray-600" }), _jsx("span", { className: "text-sm", children: user.email })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Phone, { className: "w-3 h-3 text-gray-600" }), _jsx("span", { className: "text-sm", children: user.phone })] })] })) : (_jsxs("div", { className: "grid grid-cols-1 gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-gray-600", children: "\u0424\u0418\u041E" }), _jsx("p", { className: "text-base font-semibold", children: user.full_name })] }), _jsxs("div", { children: [_jsxs("p", { className: "text-sm font-medium text-gray-600 flex items-center gap-1", children: [_jsx(Mail, { className: "w-3 h-3" }), "Email"] }), _jsx("p", { className: "text-base", children: user.email })] }), _jsxs("div", { children: [_jsxs("p", { className: "text-sm font-medium text-gray-600 flex items-center gap-1", children: [_jsx(Phone, { className: "w-3 h-3" }), "\u0422\u0435\u043B\u0435\u0444\u043E\u043D"] }), _jsx("p", { className: "text-base", children: user.phone })] })] }))] }));
    if (!useCard) {
        return (_jsx("div", { className: "border-t pt-2 mt-2", children: content }));
    }
    return (_jsx(Card, { children: _jsx(CardHeader, { className: isCompact ? "pb-2" : "pb-3", children: content }) }));
}
